language: node_js
node_js: node
cache: npm

jobs:
  include:
    - stage: test
    - stage: verify definitions
      if: env(TRAVIS_COMMIT_RANGE) is present
      script: npm run verify-definitions -- $TRAVIS_COMMIT_RANGE
