language: node_js
node_js: node
cache: npm

jobs:
  include:
    - stage: test
    - stage: verify definitions
      if: type = pull_request
      script: npm run verify-definitions -- $TRAVIS_COMMIT_RANGE
